version: '3'
networks: 
    app_net:
        driver: bridge
services:
    app:
        build:
          context: .
          dockerfile: ./app/dockerfile
        container_name: app
        command: dockerize -wait tcp://db:3306 -timeout 50s node index.js
        tty: true
        networks: 
            - app_net
    nginx:
        build:
            context: .
            dockerfile: ./nginx/dockerfile
        container_name: nginx
        networks: 
            - app_net
        ports: 
            - "5000:80"
    db:
        image: mysql
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        tty: true
        volumes: 
            - /mnt/wsl/mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - app_net
    adminer:
        image: adminer
        restart: always
        ports:
            - 3001:8080
        networks: 
            - app_net